### ISSUE TITLE
$ Domain & $ OU need to define

### ISSUE THREAD

**Issue by Tusharvmankar** [engrit-illinois/Audit-MisconfiguredGpos#1]
Here in the module it is noticed we need to modify Domain & OU to get the desire output. 
your Readme file should include this.

**Comment by mmseng** [comment]
Thanks for your input.

In general, my scripts and modules are intended to be inspiration, or a jumping off point for IT Pros, and not fully supported, production scripts, as noted here: https://github.com/mmseng/code-compendium, so some of them need some customization to the default parameters for use in your own environment.

That being said I still try to make them as usable and generalized as time permits, so I went ahead and updated the README to be more clear that some of the parameter defaults should be customized in the PSM1 file: https://github.com/engrit-illinois/Audit-MisconfiguredGpos/commit/f80351842b02f5cc19059d69ea208d3f2f6a1b04
